### ISSUE TITLE
Wrong colour order?

### ISSUE THREAD

**Issue by jdieg0** [pimoroni/dot3k#4]
I unpacked the Display-O-Tron 3000 an hour ago, so correct me if I'm wrong. I'm a bit confused by the dot3k.backlight.rgb command, because actually the order of the parameters is dot3k.backlight.rgb(red, BLUE, GREEN). I've noticed this in the basic example 'joystick.py'. Pushing the joystick down results in blue backlight (b.rgb(0,255,0)), pushing it left results in green light (b.rgb(0,0,255)).

**Comment by Gadgetoid** [comment]
Ahoy!

You probably have one of the very, very first Display-O-Tron 3000 boards we produced- treasure it! The LEDs used on those actually had a physically different pixel order.

I will be adding a new feature to the dot3k library ASAP to allow you to specify that your Dot3k is RBG so everything works as normal!

**Comment by jdieg0** [comment]
Thanks for the info! How many RBG dot3k boards are out there? :)

**Comment by Gadgetoid** [comment]
Honestly, I don't know! I'm not sure I could even make an educated guess.

**Comment by Gadgetoid** [comment]
Fixed in b1890c6ad113d739f13443ea1f3a62dd903fc1f9

After importing dot3k.backlight call:

    dot3k.backlight.use_rbg()

And the register assignments for the Green and Blue pixels will be swapped.

**Comment by andrewpmiller** [comment]
I just discovered this glitch on mine as well... sorry @jdieg0 - yours is not _as_ rare as you thought. Thanks for fixing this, @Gadgetoid!

**Comment by khargy** [comment]
I'm having this same issue... I see the code update on github, but I can't figure out how to get pip to download it. I even tried an uninstall  and new install and it still doesn't seem to have the lastest code in "/usr/local/lib/python2.7/dist-packages/dot3k"

**Comment by Gadgetoid** [comment]
Ahoy! Sorry, the code isn't yet in pip- I don't like to push stuff to there too quickly, just in case I make a horrible mess of it and break the library or in case some other changes come along that I can batch into an update. Nobody has come back with trouble in a week though, so I'll try and get it pip'd ASAP.

**Comment by khargy** [comment]
Ah no problem... I'm new to Python and Pip so I figured I was doing something wrong :)

**Comment by zoologies** [comment]
Hi,
I am having this problem too. Is the code in pip yet?
Also, none of the lcd functions seem to display anything on the display - I can change the background colours and the bar graph, but no text :-(

**Comment by Gadgetoid** [comment]
Honestly, I can't remember if I pip'd it! I'll check.

**Comment by Gadgetoid** [comment]
Yup, it's apparently pip'd - it's there in the change-log.
